/**
 * SafepayButton React component created via the @sfpy/checkout-components zoid driver.
 *
 * This module wraps the Safepay checkout button component using the zoid pattern.
 * It renders a branded Safepay pay button that opens an embedded checkout iframe
 * when clicked, handling the payment flow within the same page context.
 *
 * Used in the consultation booking overlay payment step (Step 3) to collect
 * consultation fees before allowing access to the Cal.com scheduling interface.
 *
 * @module SafepayButton
 * @see {@link /Users/sobanahmad/Work/AR&CO/Docs/safepay/safepay-integration-reference.md} - Safepay integration reference
 * @see {@link https://safepay-docs.netlify.app/} - Official Safepay documentation
 *
 * @example
 * ```tsx
 * import SafepayButton from '@/lib/safepay/safepay-button';
 *
 * function PaymentStep() {
 *   const handlePaymentSuccess = (data: { payment: Record<string, unknown> }) => {
 *     console.log('Payment successful:', data);
 *     // Move to next step (Cal.com scheduling)
 *   };
 *
 *   const handleCancel = () => {
 *     console.log('Payment cancelled');
 *     // Allow user to retry or go back
 *   };
 *
 *   return (
 *     <SafepayButton
 *       env="sandbox"
 *       client={{ sandbox: "pub_xxx" }}
 *       style={{ mode: "dark", size: "large" }}
 *       orderId="CON-2026-0001"
 *       source="website"
 *       payment={{ currency: "PKR", amount: 50000 }}
 *       onPayment={handlePaymentSuccess}
 *       onCancel={handleCancel}
 *     />
 *   );
 * }
 * ```
 *
 * @example
 * ```tsx
 * // Production environment configuration
 * <SafepayButton
 *   env="production"
 *   client={{ production: process.env.NEXT_PUBLIC_SAFEPAY_PUBLIC_KEY }}
 *   style={{ mode: "light", size: "medium", variant: "primary" }}
 *   orderId={consultationId}
 *   source="consultation_booking"
 *   payment={{
 *     currency: "PKR",
 *     amount: 50000 // Amount in PKR (major unit)
 *   }}
 *   onPayment={(data) => {
 *     // Save payment data and proceed to scheduling
 *     savePaymentData(data);
 *     setCurrentStep(4); // Move to Cal.com step
 *   }}
 *   onCancel={() => {
 *     // Handle cancellation
 *     toast.error('Payment cancelled. Please try again.');
 *   }}
 * />
 * ```
 */

import * as React from 'react';
import * as ReactDOM from 'react-dom';

// @sfpy/checkout-components is a UMD bundle that requires `window` at
// evaluation time. Turbopack may wrap require() results under `.default`.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const safepayRaw = require('@sfpy/checkout-components');
const safepay = (safepayRaw.default ?? safepayRaw) as
  typeof import('@sfpy/checkout-components').default;

/**
 * SafepayButton component - Branded payment button with embedded checkout.
 *
 * Generated by the zoid driver pattern. Renders a React component that opens
 * an embedded Safepay checkout iframe when clicked.
 *
 * @type {React.ComponentType<import('@sfpy/checkout-components').SafepayButtonProps>}
 */
const SafepayButton = safepay.Button.driver('react', {
  React,
  ReactDOM,
});

export default SafepayButton;
